PENCIL: dict = {
    "name": "Pencil",
    "recommended_value_zones": 7,
    "recommended_palette_size": 6,
    "edge_strategy": "hatching",
    "texture_strategy": "crosshatch",
    "stages": [
        {
            "order": 1,
            "name": "Construction lines",
            "description": "Lightly sketch the major proportions with a 2H pencil. Use construction lines (centre line, bounding box, negative shapes). Don't draw what you think you see — measure.",
            "why": "Your brain stores symbols — 'an eye', 'a tree' — and will draw the symbol instead of what is in front of you unless you force it to measure. Construction lines and negative shapes are tricks to bypass the symbol and see actual proportions.",
            "analysis_layers": ["level_1_outlines"],
        },
        {
            "order": 2,
            "name": "Contour refinement",
            "description": "Refine the outline with an HB pencil. Vary line weight: heavier on shadow-side contours, lighter on light-side edges. No outlines in finished drawings — vary the weight.",
            "why": "In the real world there are no outlines — only places where one value meets another. A line that is heavier on the shadow side already encodes the lighting, so your 'outline' starts doing the work of tone before you shade anything.",
            "analysis_layers": ["outlines_primary", "outlines_primary_secondary"],
        },
        {
            "order": 3,
            "name": "Value mass lay-in",
            "description": "With a 2B or 4B, block the shadow masses with consistent hatching direction. Identify the 3 major zones: dark, mid, light. Go darker than you think.",
            "why": "Beginners' drawings look washed-out for one reason: fear of darks. Graphite reads roughly one value lighter than it feels while you apply it, so 'darker than you think' is not bravado — it is calibration.",
            "analysis_layers": ["level_2_values", "level_3_values"],
        },
        {
            "order": 4,
            "name": "Hatching development",
            "description": "Build value through layered hatching at 45° or following the form. Crosshatch for darker tones. Keep strokes even in pressure, vary in density.",
            "why": "Layered hatching builds value the way glazes do in painting — each pass darkens predictably, which pressing harder never does. Strokes that follow the form also describe its surface direction for free, like contour lines on a map.",
            "analysis_layers": ["level_4_values"],
        },
        {
            "order": 5,
            "name": "Edge refinement",
            "description": "Use a kneaded eraser to lift highlights. Harden primary contours with a sharp 4B. Blend mid-tones with a tortillon in one direction only.",
            "why": "The eraser is a drawing tool, not a correction tool — lifting a highlight out of tone reads more naturally than leaving paper around it. One-direction blending matters because scrubbing back and forth destroys the hatching structure you spent stage 4 building.",
            "analysis_layers": ["outlines_detailed", "level_5_values"],
        },
        {
            "order": 6,
            "name": "Accents and texture",
            "description": "Add the darkest dark (pure 8B or 9B). Re-establish lost edges. Add micro-texture in decorative areas. Final: pull highlights with an eraser.",
            "why": "A drawing's punch comes from its extremes: the single darkest accent and the cleanest lifted highlight, placed last so nothing dulls them. Everything between those two notes now reads richer by comparison.",
            "analysis_layers": ["level_5_outlines"],
        },
    ],
    "instructions": {
        "palette_note": "Use H grades for light, B grades for dark. Never press hard — layer instead.",
        "edge_note": "Pencil edges: sharp where light meets form, lost where shadow meets shadow.",
        "value_note": "Your darkest dark is your most expressive tool. Reserve 6B/8B for the deepest shadows only.",
    },
}
